### ISSUE TITLE
deprecate vext.gi? pygobject appears to work in a virtualenv now

### ISSUE THREAD

**Issue by graingert** [stuaxo/vext#69] opened 2020-09-20 10:29 UTC
```
$ sudo apt install libcairo2-dev libgirepository1.0-dev gir1.2-gtk-3.0
$ pip install pygobject
Collecting pygobject
  Downloading PyGObject-3.38.0.tar.gz (712 kB)
     |████████████████████████████████| 712 kB 2.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Processing /home/graingert/.cache/pip/wheels/c2/06/6b/839c0659d8100837a927dae943b56669a56eb1da7ab66fb81a/pycairo-1.19.1-cp38-cp38-linux_x86_64.whl
Building wheels for collected packages: pygobject
  Building wheel for pygobject (PEP 517) ... done
  Created wheel for pygobject: filename=PyGObject-3.38.0-cp38-cp38-linux_x86_64.whl size=866287 sha256=5ead4cacee19bd4c68227ef1bd321b24b3656a2127734a0df6c64a73e51a3937
  Stored in directory: /home/graingert/.cache/pip/wheels/18/89/ef/36593f406fc32e8b8db27dbc2529ea812145bcea1a1b93118d
Successfully built pygobject
Installing collected packages: pycairo, pygobject
Successfully installed pycairo-1.19.1 pygobject-3.38.0
```

```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi
<module 'gi' from '/home/graingert/.virtualenvs/pygobject/lib/python3.8/site-packages/gi/__init__.py'> 
```

**Comment by stuaxo** [comment] 2020-09-21 11:16
I'm up for this, can you confirm if it works in all three major OSs, Linux., OSX and Windows ?

**Comment by graingert** [comment] 2020-09-21 11:21
@stuaxo I can't check it directly on mac and windows, but here's a stackoverflow post that seems to show that it works on macos: https://stackoverflow.com/a/37648798/833093

**Comment by nathanael-naeri** [comment] 2021-09-09 15:52
Hi, I'd just like to mention that using `vext.gi` is the only workaround I've found to:

- use gedit with plugins when gedit is started from a command line where a Python virtual environment is active (a use case that occurs frequently in my daily work, when I'm writing or modifying Python programs in a virtual environment using gedit)
- without triggering what appears to be a (very annoying) [miscommunication problem](https://discourse.gnome.org/t/using-gedit-plugins-in-python-virtual-environments/7387) between gedit's Git and File Browser plugins

The other potential workaround, installing PyGObject in the virtual environment, does trigger that miscommunication problem, which is a pain if you want to use the Git plugin. Something to do with a message bus, I'm not sure...

So as a user, I'm not keen on seeing `vext.gi` potentially deprecated in favor of installing PyGObject. But then again I understand it's a problem with gedit and/or PyGObject, not Vext.

**Comment by stuaxo** [comment] 2021-09-09 19:30
OK, let's close this ticket since it's still useful.
I also find it handy sometimes as it can pretty quick to install.

**Closed as completed by stuaxo** 2021-09-09 19:30 UTC

**Comment by stuaxo** [comment] 2021-09-09 20:08
What we *really* need is for WHL installation to be solved pygobject, pycairo and friends.

Things are partially there but more work is needed.

When it comes to Gedit and others: I really wish they had standard python environments where pip and friends could be used more easily.

I'm curious how you use vext.gi with Gedit ?

**Comment by nathanael-naeri** [comment] 2022-02-25 19:07
> I'm curious how you use vext.gi with Gedit ?

Sorry for the late reply @stuaxo. I am not using vext.gi with Gedit proper, but with its plugins. I use a lot of plugins from the list in the "Preferences > Plugins" section of the application. Gedit appears to require PyGObject for its plugin feature: it complains about PyGObject being missing when started up in a virtual environment where it is not installed. Hence why I'm using vext.gi to access the system's PyGObject, when I work with Gedit in virtual environments.

**Comment by nathanael-naeri** [comment] 2022-10-24 01:20
I'm coming back to this discussion to report that I've found a way to not need `vext.gi` for the weird use case I reported previously. As a result, I no longer have any objection to `vext.gi` becoming deprecated in favor of installing PyGObject in the virtual environment (which I can confirm works). Maybe `vext.gi` is still useful to other users, though.

(My weird use case was using `vext.gi` to allow some of Gedit's plugins, which depend on PyGObject, to run successfully when I start Gedit from the command line in a virtual environment where PyGObject is not installed. Now, instead of using `vext.gi`, I temporarily reset PATH and PYTHONHOME to the values they have outside the virtual environment before starting Gedit - through a custom script, although an alias or a shell function would work as well. This makes Gedit's plugins use the system's Python, including PyGObject.)

**Comment by stuaxo** [comment] 2022-10-24 12:43
I've used vext.gi for the same weird use-case :)

Feel free to share notes.

I have really little time to maintain vext.gi, I pretty much do the minimum to keep it working.

It's definitely still convenient even in cases where pygobject could work, since it's less heavy than installing the whole of pygobject.

**Comment by stuaxo** [comment] 2022-10-24 14:16
OT: I wish that for gedit plugins python could be more fully featured, maybe each plugin could be in a venv or at least all plugins in one, so you could pip install dependencies.
