### ISSUE TITLE
Can't install vext.PyQt5 with python3.5 virtualenv

### ISSUE THREAD

**Issue by PaulEcoffet** [stuaxo/vext#37] opened 2016-11-17 14:21 UTC
Good afternoon,

I am trying to install vext.PyQt5 on my python3.5 virtual env and I am having issues with the building of the wheel. Apparently the PYTHONPATH of the virtualenv is empty (which seems quite normal actually) but it makes vext.PyQt5 wheel creation fails.

The suggestion to look at https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations to see what could be going on didn't helped me at all.

I have installed python3-PyQt5 with apt-get on my ubuntu14.04 and it works perfectly outside of the venv.

It seems that there is a configuration issue in vext.pyqt5 installation script for python3.5.

Thank you for your help.

Here is the console output
```
$ pip install --force-reinstall --upgrade vext.pyqt5 
Collecting vext.pyqt5
  Using cached vext.pyqt5-0.5.20.tar.gz
Collecting vext>=0.5.20 (from vext.pyqt5)
Collecting ruamel.yaml>=0.11.10 (from vext>=0.5.20->vext.pyqt5)
  Using cached ruamel.yaml-0.12.18-cp35-cp35m-manylinux1_x86_64.whl
Building wheels for collected packages: vext.pyqt5
  Running setup.py bdist_wheel for vext.pyqt5 ... error
  Complete output from command /home/ecoffet/.virtualenvs/env/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z459zc3b/vext.pyqt5/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmph0q3mf56pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  installing to build/bdist.linux-x86_64/wheel
  running install
  vext.gi Install
  Requirement already satisfied: vext>=0.5.20 in /home/ecoffet/.virtualenvs/env/lib/python3.5/site-packages
  Requirement already satisfied: ruamel.yaml>=0.11.10 in /home/ecoffet/.virtualenvs/env/lib/python3.5/site-packages (from vext>=0.5.20)
  Checking .pth file support in build/bdist.linux-x86_64/wheel/
  /home/ecoffet/.virtualenvs/env/bin/python3.5 -E -c pass
  TEST FAILED: build/bdist.linux-x86_64/wheel/ does NOT support .pth files
  error: bad install directory or PYTHONPATH
  
  You are attempting to install a package to a directory that is not
  on PYTHONPATH and which Python does not read ".pth" files from.  The
  installation directory you specified (via --install-dir, --prefix, or
  the distutils default setting) was:
  
      build/bdist.linux-x86_64/wheel/
  
  and your PYTHONPATH environment variable currently contains:
  
      ''
  
  Here are some of your options for correcting the problem:
  
  * You can choose a different installation directory, i.e., one that is
    on PYTHONPATH or supports .pth files
  
  * You can add the installation directory to the PYTHONPATH environment
    variable.  (It must then also be on PYTHONPATH whenever you run
    Python and want to use the package(s) you are installing.)
  
  * You can set up the installation directory to support ".pth" files by
    using one of the approaches described here:
  
    https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations
  
  
  Please make the appropriate changes for your system and try again.
  
  ----------------------------------------
  Failed building wheel for vext.pyqt5

```

**Comment by stuaxo** [comment] 2016-12-20 02:22
Hi,
    Sorry this has taken ages for me to look at, have been uber busy.
Looks like there may be som issue with new pip stuff + wheels, I'll need to find some time to get an Ubuntu 14.04 vm and try this..

S

**Comment by stuaxo** [comment] 2017-01-06 21:19
Sorry for the delay ... things have been really busy outside of vext :)

I've tested this in Ubuntu 16.10 and it works, however the messages during install are the same as the one you pasted.

The messages during install are a little deceptive, and should probably be suppressed.

In the virtualenv - 

Try running the same python snippet as below and see what the output is like

```
>>> from PyQt5 import QtCore
>>> QtCore.__file__
'/usr/lib/python3/dist-packages/PyQt5/QtCore.cpython-35m-x86_64-linux-gnu.so'
```

Also, check the output of

```$ vext -l```

to see if pyqt5.vext is listed: 

```
pyqt5.vext
```

**Comment by stuaxo** [comment] 2017-08-16 10:18
I'm going to close this since I can't reproduce this, please reopen if it is still a problem.

**Closed as completed by stuaxo** 2017-08-16 10:18 UTC
